// engine.test.js - KeySwitch Desktop
// Pure-JS tests for the conversion + detection engine (no Electron / no
// native modules needed — runs on any OS with `npm test`).
'use strict';

const { test } = require('node:test');
const assert = require('node:assert');

const { convertFullText } = require('../src/engine/shared_logic');
const dict = require('../src/engine/dictionaries');
const keymap = require('../src/engine/keymap');
const { AutocorrectEngine, computeRunStart } = require('../src/engine/autocorrect-engine');

// ---------------------------------------------------------------------------
// convertFullText
// ---------------------------------------------------------------------------
test('convertFullText: EN-layout gibberish to Hebrew', () => {
  assert.strictEqual(convertFullText('akuo', 'en2he'), 'שלום');
});

test('convertFullText: Hebrew-layout gibberish to English', () => {
  assert.strictEqual(convertFullText('יקךךם', 'he2en').toLowerCase(), 'hello');
});

test('convertFullText: CapsLock gibberish converts to Hebrew', () => {
  assert.strictEqual(convertFullText('AKUO', 'en2he'), 'שלום');
});

// ---------------------------------------------------------------------------
// classify
// ---------------------------------------------------------------------------
test('classify: detects wrong-layout Hebrew typed on EN keyboard', () => {
  const r = dict.classify('akuo', false);
  assert.deepStrictEqual(r, { kind: 'wrong', lang: 'he', direction: 'en2he' });
});

test('classify: detects wrong-layout English typed on HE keyboard', () => {
  const r = dict.classify('יקךךם', false);
  assert.deepStrictEqual(r, { kind: 'wrong', lang: 'en', direction: 'he2en' });
});

test('classify: correct words are not flagged', () => {
  assert.strictEqual(dict.classify('שלום', false).kind, 'correct');
  assert.strictEqual(dict.classify('hello', false).kind, 'correct');
});

test('classify: intentional uppercase is left alone when CapsLock is off', () => {
  assert.strictEqual(dict.classify('AKUO', false).kind, 'unknown');
});

test('classify: uppercase gibberish IS flagged when CapsLock is on', () => {
  const r = dict.classify('AKUO', true);
  assert.deepStrictEqual(r, { kind: 'wrong', lang: 'he', direction: 'en2he' });
});

// The keys , . ; type the Hebrew letters ת ץ ף, and / types q when flipped
// back — so those characters are LETTERS of the intended word, not
// punctuation to strip. Regression tests for words that were never detected.
test('classify: Hebrew word ending in ת (comma key) is detected — זאת = "zt,"', () => {
  assert.deepStrictEqual(dict.classify('zt,', false), { kind: 'wrong', lang: 'he', direction: 'en2he' });
});

test('classify: Hebrew word starting with ת (comma key) is detected — תודה = ",usv"', () => {
  assert.deepStrictEqual(dict.classify(',usv', false), { kind: 'wrong', lang: 'he', direction: 'en2he' });
});

test('classify: Hebrew word ending in ף (semicolon key) is detected — כיף = "fh;"', () => {
  assert.deepStrictEqual(dict.classify('fh;', false), { kind: 'wrong', lang: 'he', direction: 'en2he' });
});

test('classify: correctly-typed English with real trailing punctuation stays correct', () => {
  assert.strictEqual(dict.classify('hello,', false).kind, 'correct');
  assert.strictEqual(dict.classify('nice.', false).kind, 'correct');
});

// ---------------------------------------------------------------------------
// extended word lists (generated by tools/generate-wordlists.js)
// ---------------------------------------------------------------------------
test('wordlists-extra: at least 15000 added words per language', () => {
  const extra = require('../src/engine/wordlists-extra');
  assert.ok(extra.EXTRA_EN.length >= 15000, `EXTRA_EN has only ${extra.EXTRA_EN.length}`);
  assert.ok(extra.EXTRA_HE.length >= 15000, `EXTRA_HE has only ${extra.EXTRA_HE.length}`);
});

test('wordlists-extra: no added word collides with the other language (go/עם rule)', () => {
  const extra = require('../src/engine/wordlists-extra');
  const fullEN = new Set(dict.FULL_EN);
  const fullHE = new Set(dict.FULL_HE);
  const HE_ONLY = /^[א-ת]+$/;
  for (const w of extra.EXTRA_EN) {
    const flip = dict.swapLayout(w, 'en2he');
    if (!HE_ONLY.test(flip)) continue;
    assert.ok(!fullHE.has(flip), `EN "${w}" flips to Hebrew word "${flip}"`);
    let s = flip;
    for (let i = 0; i < 2 && s.length > 3 && dict.HE_PREFIXES.indexOf(s[0]) >= 0; i++) {
      s = s.slice(1);
      assert.ok(!fullHE.has(s), `EN "${w}" flips to prefixed Hebrew word "${flip}"`);
    }
  }
  for (const h of extra.EXTRA_HE) {
    const flip = dict.swapLayout(h, 'he2en').toLowerCase();
    assert.ok(!fullEN.has(flip), `HE "${h}" flips to English word "${flip}"`);
    for (const p of dict.HE_PREFIXES) {
      const pf = dict.swapLayout(p + h, 'he2en').toLowerCase();
      assert.ok(!fullEN.has(pf), `HE "${h}" prefix-flips to English word "${pf}"`);
    }
  }
});

test('wordlists-extra: ambiguous pair go/עם stays untouched in both languages', () => {
  assert.strictEqual(dict.classify('go', false).kind, 'correct');
  assert.strictEqual(dict.classify('עם', false).kind, 'correct');
});

// ---------------------------------------------------------------------------
// keymap
// ---------------------------------------------------------------------------
test('keymap: every letter key resolves in both layouts', () => {
  const K = keymap.UiohookKey;
  for (const name of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') {
    const en = keymap.keyToChar(K[name], 'en', false, false);
    const he = keymap.keyToChar(K[name], 'he', false, false);
    assert.strictEqual(en, name.toLowerCase());
    assert.ok(he && he !== en, `Hebrew mapping missing for ${name}`);
  }
});

test('keymap: Hebrew layout with CapsLock produces capital Latin letters', () => {
  const K = keymap.UiohookKey;
  assert.strictEqual(keymap.keyToChar(K.A, 'he', false, true), 'A');
  assert.strictEqual(keymap.keyToChar(K.A, 'he', false, false), 'ש');
});

test('keymap: shift symbols on EN layout', () => {
  const K = keymap.UiohookKey;
  assert.strictEqual(keymap.keyToChar(K['1'], 'en', true, false), '!');
  assert.strictEqual(keymap.keyToChar(K.Slash, 'en', true, false), '?');
});

// ---------------------------------------------------------------------------
// computeRunStart
// ---------------------------------------------------------------------------
test('computeRunStart: run starts after a correctly-typed opposite-script word', () => {
  const s = 'שלום akuo';
  const rs = computeRunStart(s, 0, s.length, 'en2he');
  assert.strictEqual(s.slice(rs), 'akuo');
});

test('computeRunStart: whole run converts when everything is wrong-layout', () => {
  const s = 'akuo kv';
  const rs = computeRunStart(s, 0, s.length, 'en2he');
  assert.strictEqual(rs, 0);
});

// ---------------------------------------------------------------------------
// AutocorrectEngine end-to-end with a fake native layer
// ---------------------------------------------------------------------------
function makeFakeNative({ layout = 'en', caps = false } = {}) {
  const calls = { backspaces: 0, typed: '', capsToggles: 0, layoutSet: [] };
  return {
    calls,
    isSupported: true,
    getForegroundWindowId: () => 'win-1',
    getForegroundLayout: () => layout,
    setForegroundLayout: (lang) => { calls.layoutSet.push(lang); layout = lang; return true; },
    isCapsLockOn: () => caps,
    toggleCapsLock: () => { calls.capsToggles++; caps = !caps; },
    sendUnicodeText: (t) => { calls.typed += t; },
    sendBackspaces: (n) => { calls.backspaces += n; },
    // Atomic erase+retype (production path); feeds the same counters the
    // assertions check.
    replaceText: (n, t) => { calls.backspaces += n; calls.typed += t; },
    sendCtrlCombo: () => {},
    beep: () => {},
    VK: {}
  };
}

function makeFakeSettings(overrides = {}) {
  const { EventEmitter } = require('events');
  const em = new EventEmitter();
  const data = { autocorrectEnabled: true, primaryLang: 'he', acWordState: {}, ...overrides };
  return {
    get: (k) => data[k],
    set: (k, v) => { data[k] = v; em.emit('change', k, v); },
    on: (ev, cb) => em.on(ev, cb)
  };
}

function typeWord(engine, word) {
  engine._syncWindow();
  engine.lastKeyTime = Date.now();
  for (const ch of word) engine._appendChar(ch);
  engine._appendChar(' ');
  engine.evaluate();
}

test('engine: fixes wrong-layout word and switches keyboard to Hebrew', () => {
  const native = makeFakeNative({ layout: 'en', caps: false });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  const events = [];
  engine.on('corrected', (e) => events.push(e));

  typeWord(engine, 'akuo');

  assert.strictEqual(native.calls.backspaces, 5); // 'akuo' + trailing space
  assert.strictEqual(native.calls.typed, 'שלום ');
  assert.deepStrictEqual(native.calls.layoutSet, ['he']);
  assert.strictEqual(native.calls.capsToggles, 0);
  assert.strictEqual(events.length, 1);
  assert.strictEqual(events[0].converted, 'שלום');
  assert.strictEqual(events[0].layoutSwitched, true);
});

test('engine: CapsLock slip — turns CapsLock off, keeps already-correct layout', () => {
  const native = makeFakeNative({ layout: 'he', caps: true });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  const events = [];
  engine.on('corrected', (e) => events.push(e));

  typeWord(engine, 'AKUO'); // what CapsLock on the Hebrew layout puts on screen

  assert.strictEqual(native.calls.capsToggles, 1, 'CapsLock must be toggled off');
  assert.deepStrictEqual(native.calls.layoutSet, [], 'layout already Hebrew — must not switch');
  assert.strictEqual(native.calls.typed, 'שלום ');
  assert.strictEqual(events[0].capsFixed, true);
  assert.strictEqual(events[0].layoutSwitched, false);
});

test('engine: CapsLock slip on wrong layout — caps off AND layout switched', () => {
  const native = makeFakeNative({ layout: 'en', caps: true });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'AKUO');

  assert.strictEqual(native.calls.capsToggles, 1);
  assert.deepStrictEqual(native.calls.layoutSet, ['he']);
});

test('engine: revert restores original text, layout and CapsLock', () => {
  const native = makeFakeNative({ layout: 'en', caps: true });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'AKUO');
  native.calls.typed = '';
  native.calls.backspaces = 0;

  const ok = engine.revertLastFix();
  assert.strictEqual(ok, true);
  assert.strictEqual(native.calls.backspaces, 5); // 'שלום' + space
  assert.strictEqual(native.calls.typed, 'AKUO ');
  assert.strictEqual(native.calls.capsToggles, 2); // back on
  assert.deepStrictEqual(native.calls.layoutSet, ['he', 'en']); // switched back
  assert.strictEqual(engine.lastFix, null);
});

test('engine: rejection suppresses the same word afterwards', () => {
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'akuo');
  engine.revertLastFix();

  native.calls.typed = '';
  engine.cooldownUntil = 0; // skip the 30s cooldown for the test
  engine.resetRun();
  typeWord(engine, 'akuo');
  assert.strictEqual(native.calls.typed, '', 'suppressed word must not be re-corrected');
});

test('engine: correct words build confidence that blocks a following fix', () => {
  const native = makeFakeNative({ layout: 'he' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'שלום'); // correct Hebrew → confidence 1
  typeWord(engine, 'יקךךם'); // would be wrong/he2en, but confidence blocks it
  assert.strictEqual(native.calls.typed, '');
});

test('engine: confidence is cleared on run reset so detection stays live after returning to a field', () => {
  // Regression test for the "sometimes stops auto-correcting when I leave and
  // come back to the same field" bug. Build up confidence, then reset the run
  // (as happens on a mouse click / focus change / typing gap on the SAME
  // window), and confirm the next mistake is still corrected.
  const native = makeFakeNative({ layout: 'he' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'שלום');   // confidence 1 in this window
  engine.resetRun();          // left & returned to the same field / new burst
  native.calls.typed = '';

  typeWord(engine, 'יקךךם');  // 'hello' typed on the Hebrew layout → must correct
  assert.strictEqual(native.calls.typed.trim(), 'Hello'); // single word → capitalized
});

test('engine: does not fire on a word the dictionaries do not know', () => {
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  typeWord(engine, 'xkcd');
  assert.strictEqual(native.calls.typed, '');
});

test('engine: the persisted rejection map is pruned and never grows without bound', () => {
  const native = makeFakeNative({ layout: 'en' });
  const settings = makeFakeSettings();
  // Seed a large map: many expired one-off rejections (droppable) plus a few
  // permanent ones (count >= 3) that must be kept.
  const state = {};
  const old = Date.now() - 31 * 60 * 1000; // older than the 30-min suppress window
  for (let i = 0; i < 800; i++) state['h' + i] = { count: 1, last: old };
  state['keep1'] = { count: 3, last: old };
  state['keep2'] = { count: 5, last: old };
  settings.set('acWordState', state);

  const engine = new AutocorrectEngine({ native, settings });

  const keys = Object.keys(engine.wordState);
  assert.ok(keys.length < 800, `expired one-offs must be pruned (kept ${keys.length})`);
  assert.ok(engine.wordState.keep1 && engine.wordState.keep2, 'permanent entries must survive');
});

// Drive the engine through the REAL keydown path (guards, lag gate, layout
// checks) instead of _appendChar. `time` simulates the hook thread's event
// timestamp; omit `lagMs` for a fresh event.
function pressKey(engine, keycode, { shiftKey = false, lagMs = 0 } = {}) {
  engine._onKeydown({
    keycode, shiftKey, ctrlKey: false, altKey: false, metaKey: false,
    time: Date.now() - lagMs
  });
}

test('engine: stale space event (processing lag) skips the correction instead of erasing blind', () => {
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  // 'akuo' typed through the real keydown path with fresh timestamps
  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k);
  // The space arrives 500ms late — the user may have typed more by now, so
  // injecting a correction could erase the wrong characters. Must skip.
  pressKey(engine, keymapK.Space, { lagMs: 500 });
  assert.strictEqual(native.calls.typed, '', 'late-processed space must not trigger injection');

  // A FRESH space right after corrects normally — the gate is per-event.
  pressKey(engine, keymapK.Space);
  assert.ok(native.calls.typed.includes('שלום'), 'fresh space must still correct');
});

test('engine: a wall-clock step does not permanently disable detection', () => {
  // Regression test for the "sometimes it just stops correcting" bug: the
  // lag-gate baseline was the ALL-TIME minimum of (Date.now() - event.time).
  // Date.now() is NTP-disciplined (steps on time sync / resume from sleep)
  // while hook timestamps come from the tick counter, so after any forward
  // wall-clock step >150ms every event looked "late" forever and evaluation
  // was silently skipped until the app restarted.
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  // Calibrate the baseline with fresh events (a word no dictionary knows, so
  // no correction fires and the fake layout stays 'en'), then the wall clock
  // steps forward 5s: every event from here on reports a constant 5s "lag".
  for (const k of [keymapK.X, keymapK.K, keymapK.C, keymapK.D]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);
  engine.resetRun();

  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k, { lagMs: 5000 });
  pressKey(engine, keymapK.Space, { lagMs: 5000 });
  assert.strictEqual(native.calls.typed, '', 'right after the step the gate correctly holds');

  // The apparent lag persists past LAG_RECAL_MS — real event-loop lag cannot
  // do that (processing events proves the loop is live), so the engine must
  // re-anchor its baseline and come back to life instead of staying dead.
  engine._lagSince = Date.now() - 2500;
  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k, { lagMs: 5000 });
  pressKey(engine, keymapK.Space, { lagMs: 5000 });
  assert.ok(native.calls.typed.includes('שלום'),
    'detection must recover after the clocks are re-anchored');
});

test('engine: a backward wall-clock step re-anchors immediately and detection stays live', () => {
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.X, keymapK.K, keymapK.C, keymapK.D]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);
  engine.resetRun();

  // Wall clock steps BACK 5s → skew shrinks below the baseline. That must be
  // adopted as the new baseline on the spot (negative lag means "impossibly
  // early", not "late"), so the very next word still corrects.
  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k, { lagMs: -5000 });
  pressKey(engine, keymapK.Space, { lagMs: -5000 });
  assert.ok(native.calls.typed.includes('שלום'),
    'a backward clock step must not disturb detection at all');
});

test('engine: real Backspace right after a correction is processed once echoes are consumed', () => {
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'akuo'); // buffer is now 'שלום '
  assert.strictEqual(engine.buffer, 'שלום ');

  // The full echo set of our own batch — 5 Backspaces ('akuo ' erased) and
  // 5 keycode-0 unicode downs ('שלום ' typed) — is swallowed…
  for (let i = 0; i < 5; i++) pressKey(engine, keymapK.Backspace);
  assert.strictEqual(engine.buffer, 'שלום ', 'echo backspaces must not touch the buffer');
  for (let i = 0; i < 5; i++) pressKey(engine, 0);
  assert.strictEqual(engine._injectGuard, null, 'guard must disarm once every echo is consumed');

  // …but the NEXT Backspace is the user's and must take effect.
  pressKey(engine, keymapK.Backspace);
  assert.strictEqual(engine.buffer, 'שלום', 'a real backspace after the echoes must be processed');
});

test('engine: blocked injection (elevated window) records nothing and eats no keys', () => {
  const native = makeFakeNative({ layout: 'en' });
  native.replaceText = () => false; // UIPI: SendInput injected nothing
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  const events = [];
  engine.on('corrected', (e) => events.push(e));

  typeWord(engine, 'akuo');

  assert.strictEqual(events.length, 0, 'no corrected event for a fix that never reached the screen');
  assert.strictEqual(engine.lastFix, null, 'nothing to revert');
  assert.strictEqual(engine._injectGuard, null, 'guard must be disarmed — no echoes are coming');
  assert.deepStrictEqual(native.calls.layoutSet, [], 'layout must not be switched');
});

test('engine: third keyboard layout (not he/en) is left completely alone', () => {
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'other' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k);
  assert.strictEqual(engine.buffer, '', 'keystrokes on a third layout must not be modeled');
  pressKey(engine, keymapK.Space);
  assert.strictEqual(native.calls.typed, '', 'no correction may fire on a third layout');
});

test('engine: a hook event that throws inside the handler does not propagate', () => {
  const native = makeFakeNative({ layout: 'en' });
  native.getForegroundWindowId = () => { throw new Error('boom'); };
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  assert.doesNotThrow(() => pressKey(engine, require('../src/engine/keymap').UiohookKey.A));
});

test('engine: keystroke racing ahead of the correction batch is repaired, not lost', () => {
  // Regression test for the "typing while an auto-fix lands corrupts the
  // text" bug: a key pressed in the instant BEFORE our SendInput batch
  // reaches the screen first, so the batch's backspaces erase THAT key and
  // leave the first letter of the mistake behind. The hook stream is screen
  // order, so such a key arrives before the batch echoes — the engine must
  // repair the screen instead of pretending the key landed after the fix.
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k);
  pressKey(engine, keymapK.Space); // correction: erase 'akuo ' (5), type 'שלום '
  assert.strictEqual(native.calls.typed, 'שלום ');
  native.calls.typed = '';
  native.calls.backspaces = 0;

  // The raced key: its hook event arrives BEFORE the batch echoes. On screen
  // the batch erased its character and left the 'a' of 'akuo' behind.
  pressKey(engine, keymapK.D);
  assert.strictEqual(engine.buffer, 'שלום ', 'raced key must not enter the model yet');

  // Batch echoes complete (5 backspaces + 5 unicode downs) → repair fires:
  // erase leftover 'a' + 'שלום ' (6 chars), retype 'שלום ' plus the raced key
  // mapped to the layout the user meant (D on the Hebrew layout = 'ג').
  for (let i = 0; i < 5; i++) pressKey(engine, keymapK.Backspace);
  for (let i = 0; i < 5; i++) pressKey(engine, 0);
  assert.strictEqual(native.calls.backspaces, 6);
  assert.strictEqual(native.calls.typed, 'שלום ג');
  assert.strictEqual(engine.buffer, 'שלום ג');
  assert.strictEqual(engine.lastFix.typedAfter, 'ג', 'raced key must count as typed-after for revert');

  // The repair is guarded exactly like the original batch — consume its
  // echoes and confirm everything is calm and in sync.
  for (let i = 0; i < 6; i++) pressKey(engine, keymapK.Backspace);
  for (let i = 0; i < 6; i++) pressKey(engine, 0);
  assert.strictEqual(engine._injectGuard, null);
  assert.strictEqual(engine.buffer, 'שלום ג');
});

test('engine: Hebrew word typed through punctuation keys is corrected in full', () => {
  // תודה typed on the English layout is ",usv" — its first letter ת lives on
  // the comma key, which the old tokenizer refused to treat as part of a
  // word, so the word was never corrected at all.
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.Comma, keymapK.U, keymapK.S, keymapK.V]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);

  assert.strictEqual(native.calls.typed, 'תודה ');
  assert.strictEqual(native.calls.backspaces, 5); // ',usv' + trailing space
});

test('engine: English word with q typed on the Hebrew layout keeps its first letter', () => {
  // "question" on the Hebrew layout is "/וקדאןםמ" — the q lives on the '/'
  // key. The old tokenizer dropped it from the run, so the correction came
  // out as "Uestion".
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'he' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  const keys = [keymapK.Q, keymapK.U, keymapK.E, keymapK.S, keymapK.T, keymapK.I, keymapK.O, keymapK.N];
  for (const k of keys) pressKey(engine, k);
  pressKey(engine, keymapK.Space);

  assert.strictEqual(native.calls.typed, 'Question ');
  assert.strictEqual(native.calls.backspaces, 9); // '/וקדאןםמ' + trailing space
});

test('engine: English word ending in q on the Hebrew layout keeps its last letter', () => {
  // "iraq" on the Hebrew layout is "ןרש/" — the trailing q lives on the '/'
  // key. classify() already resolves the other letters to 'wrong' via a
  // misplaced Hebrew final letter (ן not at the true end) WITHOUT ever
  // looking at the '/', so the fix must still fold the '/' into the run or
  // it's dropped from the correction, leaving a stray '/' on screen.
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'he' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.I, keymapK.R, keymapK.A, keymapK.Q]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);

  assert.strictEqual(native.calls.typed, 'Iraq '); // single word → capitalized
  assert.strictEqual(native.calls.backspaces, 5); // 'ןרש/' + trailing space
});

test('engine: an out-of-dictionary word followed by real punctuation is left alone', () => {
  // Regression for "the sound plays even when nothing needed fixing": a
  // word not in either dictionary, glued to an ordinary comma/period the
  // user typed on purpose, must NOT be treated as a layout mistake just
  // because it happens to be unrecognized. Only a word that is a genuine
  // dictionary hit as EXACTLY plain+punctuation triggers a fix (see the
  // "typed through punctuation keys" tests above) — an unrecognized word
  // stays 'unknown' and is left untouched, comma and all.
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.X, keymapK.E, keymapK.R, keymapK.O, keymapK.X]) pressKey(engine, k);
  pressKey(engine, keymapK.Comma);
  pressKey(engine, keymapK.Space);

  assert.strictEqual(native.calls.typed, '', 'an unrecognized word + real punctuation must not be "corrected"');
});

test('engine: two real words joined only by a comma are not merged into one token', () => {
  // Regression for the tokenizer over-capture this session's punctuation fix
  // could have introduced: without a space, "hi,mom" must NOT be scanned as
  // one combined run (which could coincidentally flip to something bogus) —
  // the comma is a genuine boundary here since a real word ("mom") sits
  // right on its far side.
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.H, keymapK.I]) pressKey(engine, k);
  pressKey(engine, keymapK.Comma);
  for (const k of [keymapK.M, keymapK.O, keymapK.M]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);

  assert.strictEqual(native.calls.typed, '', 'hi,mom must not be reinterpreted as one gibberish token');
});

test('engine: a follow-up opposite-direction fix never re-flips the previous correction', () => {
  // Corruption regression: user types "akuo" → corrected to "שלום" and the
  // layout flips to Hebrew. They keep typing "hello", which now lands as
  // "יקךךם" on the Hebrew layout. That he2en mistake's run would start at 0
  // and drag the good "שלום" back into the conversion, turning it into
  // "Akuo". The run must be clamped to start after the prior fix's output.
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k);
  pressKey(engine, keymapK.Space); // → "שלום " on screen, layout now 'he'
  assert.strictEqual(native.calls.typed, 'שלום ');
  // consume the correction's echoes so the guard disarms cleanly
  for (let i = 0; i < 5; i++) pressKey(engine, keymapK.Backspace);
  for (let i = 0; i < 5; i++) pressKey(engine, 0);
  native.calls.typed = '';
  native.calls.backspaces = 0;

  // "hello" on the Hebrew layout → י ק ך ך ם
  for (const k of [keymapK.H, keymapK.E, keymapK.L, keymapK.L, keymapK.O]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);

  // Only the second word is re-flipped; "שלום" is untouched.
  assert.ok(!native.calls.typed.includes('Akuo'), 'the prior fix must not be re-flipped');
  assert.strictEqual(native.calls.backspaces, 6, 'only "יקךךם " (6 chars) is erased, not the whole line');
  assert.strictEqual(native.calls.typed.trim(), 'Hello'); // single word → capitalized
  assert.strictEqual(engine.buffer, 'שלום Hello ');
});

test('engine: toggling autocorrect off clears the stale run', () => {
  // While disabled the buffer stops mirroring the screen. Re-enabling within
  // the freshness window must never evaluate the leftover text.
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const settings = makeFakeSettings();
  const engine = new AutocorrectEngine({ native, settings });

  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k);
  assert.strictEqual(engine.buffer, 'akuo');

  settings.set('autocorrectEnabled', false);
  assert.strictEqual(engine.buffer, '', 'stale run must be dropped on toggle');

  settings.set('autocorrectEnabled', true);
  pressKey(engine, keymapK.Space);
  assert.strictEqual(native.calls.typed, '', 'no correction may fire from a stale buffer');
});

test('engine: unmodelable key racing the batch drops the run instead of guessing', () => {
  const keymapK = keymap.UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);
  native.calls.typed = '';
  native.calls.backspaces = 0;

  // An arrow key raced ahead of the batch: the caret moved before the
  // replacement landed, so the screen state is unknowable. No repair may be
  // injected — the run must simply be dropped.
  pressKey(engine, keymapK.ArrowLeft);
  for (let i = 0; i < 5; i++) pressKey(engine, keymapK.Backspace);
  for (let i = 0; i < 5; i++) pressKey(engine, 0);

  assert.strictEqual(native.calls.typed, '', 'no repair batch on an unknowable screen');
  assert.strictEqual(native.calls.backspaces, 0);
  assert.strictEqual(engine.buffer, '', 'run dropped');
  assert.strictEqual(engine.lastFix, null, 'nothing safe to revert');
  assert.strictEqual(engine._injectGuard, null);
});
