// engine.test.js - KeySwitch Desktop
// Pure-JS tests for the conversion + detection engine (no Electron / no
// native modules needed — runs on any OS with `npm test`).
'use strict';

const { test } = require('node:test');
const assert = require('node:assert');

const { convertFullText } = require('../src/engine/shared_logic');
const dict = require('../src/engine/dictionaries');
const keymap = require('../src/engine/keymap');
const { AutocorrectEngine, computeRunStart } = require('../src/engine/autocorrect-engine');

// ---------------------------------------------------------------------------
// convertFullText
// ---------------------------------------------------------------------------
test('convertFullText: EN-layout gibberish to Hebrew', () => {
  assert.strictEqual(convertFullText('akuo', 'en2he'), 'שלום');
});

test('convertFullText: Hebrew-layout gibberish to English', () => {
  assert.strictEqual(convertFullText('יקךךם', 'he2en').toLowerCase(), 'hello');
});

test('convertFullText: CapsLock gibberish converts to Hebrew', () => {
  assert.strictEqual(convertFullText('AKUO', 'en2he'), 'שלום');
});

// ---------------------------------------------------------------------------
// classify
// ---------------------------------------------------------------------------
test('classify: detects wrong-layout Hebrew typed on EN keyboard', () => {
  const r = dict.classify('akuo', false);
  assert.deepStrictEqual(r, { kind: 'wrong', lang: 'he', direction: 'en2he' });
});

test('classify: detects wrong-layout English typed on HE keyboard', () => {
  const r = dict.classify('יקךךם', false);
  assert.deepStrictEqual(r, { kind: 'wrong', lang: 'en', direction: 'he2en' });
});

test('classify: correct words are not flagged', () => {
  assert.strictEqual(dict.classify('שלום', false).kind, 'correct');
  assert.strictEqual(dict.classify('hello', false).kind, 'correct');
});

test('classify: intentional uppercase is left alone when CapsLock is off', () => {
  assert.strictEqual(dict.classify('AKUO', false).kind, 'unknown');
});

test('classify: uppercase gibberish IS flagged when CapsLock is on', () => {
  const r = dict.classify('AKUO', true);
  assert.deepStrictEqual(r, { kind: 'wrong', lang: 'he', direction: 'en2he' });
});

// ---------------------------------------------------------------------------
// extended word lists (generated by tools/generate-wordlists.js)
// ---------------------------------------------------------------------------
test('wordlists-extra: at least 15000 added words per language', () => {
  const extra = require('../src/engine/wordlists-extra');
  assert.ok(extra.EXTRA_EN.length >= 15000, `EXTRA_EN has only ${extra.EXTRA_EN.length}`);
  assert.ok(extra.EXTRA_HE.length >= 15000, `EXTRA_HE has only ${extra.EXTRA_HE.length}`);
});

test('wordlists-extra: no added word collides with the other language (go/עם rule)', () => {
  const extra = require('../src/engine/wordlists-extra');
  const fullEN = new Set(dict.FULL_EN);
  const fullHE = new Set(dict.FULL_HE);
  const HE_ONLY = /^[א-ת]+$/;
  for (const w of extra.EXTRA_EN) {
    const flip = dict.swapLayout(w, 'en2he');
    if (!HE_ONLY.test(flip)) continue;
    assert.ok(!fullHE.has(flip), `EN "${w}" flips to Hebrew word "${flip}"`);
    let s = flip;
    for (let i = 0; i < 2 && s.length > 3 && dict.HE_PREFIXES.indexOf(s[0]) >= 0; i++) {
      s = s.slice(1);
      assert.ok(!fullHE.has(s), `EN "${w}" flips to prefixed Hebrew word "${flip}"`);
    }
  }
  for (const h of extra.EXTRA_HE) {
    const flip = dict.swapLayout(h, 'he2en').toLowerCase();
    assert.ok(!fullEN.has(flip), `HE "${h}" flips to English word "${flip}"`);
    for (const p of dict.HE_PREFIXES) {
      const pf = dict.swapLayout(p + h, 'he2en').toLowerCase();
      assert.ok(!fullEN.has(pf), `HE "${h}" prefix-flips to English word "${pf}"`);
    }
  }
});

test('wordlists-extra: ambiguous pair go/עם stays untouched in both languages', () => {
  assert.strictEqual(dict.classify('go', false).kind, 'correct');
  assert.strictEqual(dict.classify('עם', false).kind, 'correct');
});

// ---------------------------------------------------------------------------
// keymap
// ---------------------------------------------------------------------------
test('keymap: every letter key resolves in both layouts', () => {
  const K = keymap.UiohookKey;
  for (const name of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') {
    const en = keymap.keyToChar(K[name], 'en', false, false);
    const he = keymap.keyToChar(K[name], 'he', false, false);
    assert.strictEqual(en, name.toLowerCase());
    assert.ok(he && he !== en, `Hebrew mapping missing for ${name}`);
  }
});

test('keymap: Hebrew layout with CapsLock produces capital Latin letters', () => {
  const K = keymap.UiohookKey;
  assert.strictEqual(keymap.keyToChar(K.A, 'he', false, true), 'A');
  assert.strictEqual(keymap.keyToChar(K.A, 'he', false, false), 'ש');
});

test('keymap: shift symbols on EN layout', () => {
  const K = keymap.UiohookKey;
  assert.strictEqual(keymap.keyToChar(K['1'], 'en', true, false), '!');
  assert.strictEqual(keymap.keyToChar(K.Slash, 'en', true, false), '?');
});

// ---------------------------------------------------------------------------
// computeRunStart
// ---------------------------------------------------------------------------
test('computeRunStart: run starts after a correctly-typed opposite-script word', () => {
  const s = 'שלום akuo';
  const rs = computeRunStart(s, 0, s.length, 'en2he');
  assert.strictEqual(s.slice(rs), 'akuo');
});

test('computeRunStart: whole run converts when everything is wrong-layout', () => {
  const s = 'akuo kv';
  const rs = computeRunStart(s, 0, s.length, 'en2he');
  assert.strictEqual(rs, 0);
});

// ---------------------------------------------------------------------------
// AutocorrectEngine end-to-end with a fake native layer
// ---------------------------------------------------------------------------
function makeFakeNative({ layout = 'en', caps = false } = {}) {
  const calls = { backspaces: 0, typed: '', capsToggles: 0, layoutSet: [] };
  return {
    calls,
    isSupported: true,
    getForegroundWindowId: () => 'win-1',
    getForegroundLayout: () => layout,
    setForegroundLayout: (lang) => { calls.layoutSet.push(lang); layout = lang; return true; },
    isCapsLockOn: () => caps,
    toggleCapsLock: () => { calls.capsToggles++; caps = !caps; },
    sendUnicodeText: (t) => { calls.typed += t; },
    sendBackspaces: (n) => { calls.backspaces += n; },
    // Atomic erase+retype (production path); feeds the same counters the
    // assertions check.
    replaceText: (n, t) => { calls.backspaces += n; calls.typed += t; },
    sendCtrlCombo: () => {},
    beep: () => {},
    VK: {}
  };
}

function makeFakeSettings(overrides = {}) {
  const data = { autocorrectEnabled: true, primaryLang: 'he', acWordState: {}, ...overrides };
  return {
    get: (k) => data[k],
    set: (k, v) => { data[k] = v; },
    on: () => {}
  };
}

function typeWord(engine, word) {
  engine._syncWindow();
  engine.lastKeyTime = Date.now();
  for (const ch of word) engine._appendChar(ch);
  engine._appendChar(' ');
  engine.evaluate();
}

test('engine: fixes wrong-layout word and switches keyboard to Hebrew', () => {
  const native = makeFakeNative({ layout: 'en', caps: false });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  const events = [];
  engine.on('corrected', (e) => events.push(e));

  typeWord(engine, 'akuo');

  assert.strictEqual(native.calls.backspaces, 5); // 'akuo' + trailing space
  assert.strictEqual(native.calls.typed, 'שלום ');
  assert.deepStrictEqual(native.calls.layoutSet, ['he']);
  assert.strictEqual(native.calls.capsToggles, 0);
  assert.strictEqual(events.length, 1);
  assert.strictEqual(events[0].converted, 'שלום');
  assert.strictEqual(events[0].layoutSwitched, true);
});

test('engine: CapsLock slip — turns CapsLock off, keeps already-correct layout', () => {
  const native = makeFakeNative({ layout: 'he', caps: true });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  const events = [];
  engine.on('corrected', (e) => events.push(e));

  typeWord(engine, 'AKUO'); // what CapsLock on the Hebrew layout puts on screen

  assert.strictEqual(native.calls.capsToggles, 1, 'CapsLock must be toggled off');
  assert.deepStrictEqual(native.calls.layoutSet, [], 'layout already Hebrew — must not switch');
  assert.strictEqual(native.calls.typed, 'שלום ');
  assert.strictEqual(events[0].capsFixed, true);
  assert.strictEqual(events[0].layoutSwitched, false);
});

test('engine: CapsLock slip on wrong layout — caps off AND layout switched', () => {
  const native = makeFakeNative({ layout: 'en', caps: true });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'AKUO');

  assert.strictEqual(native.calls.capsToggles, 1);
  assert.deepStrictEqual(native.calls.layoutSet, ['he']);
});

test('engine: revert restores original text, layout and CapsLock', () => {
  const native = makeFakeNative({ layout: 'en', caps: true });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'AKUO');
  native.calls.typed = '';
  native.calls.backspaces = 0;

  const ok = engine.revertLastFix();
  assert.strictEqual(ok, true);
  assert.strictEqual(native.calls.backspaces, 5); // 'שלום' + space
  assert.strictEqual(native.calls.typed, 'AKUO ');
  assert.strictEqual(native.calls.capsToggles, 2); // back on
  assert.deepStrictEqual(native.calls.layoutSet, ['he', 'en']); // switched back
  assert.strictEqual(engine.lastFix, null);
});

test('engine: rejection suppresses the same word afterwards', () => {
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'akuo');
  engine.revertLastFix();

  native.calls.typed = '';
  engine.cooldownUntil = 0; // skip the 30s cooldown for the test
  engine.resetRun();
  typeWord(engine, 'akuo');
  assert.strictEqual(native.calls.typed, '', 'suppressed word must not be re-corrected');
});

test('engine: correct words build confidence that blocks a following fix', () => {
  const native = makeFakeNative({ layout: 'he' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'שלום'); // correct Hebrew → confidence 1
  typeWord(engine, 'יקךךם'); // would be wrong/he2en, but confidence blocks it
  assert.strictEqual(native.calls.typed, '');
});

test('engine: confidence is cleared on run reset so detection stays live after returning to a field', () => {
  // Regression test for the "sometimes stops auto-correcting when I leave and
  // come back to the same field" bug. Build up confidence, then reset the run
  // (as happens on a mouse click / focus change / typing gap on the SAME
  // window), and confirm the next mistake is still corrected.
  const native = makeFakeNative({ layout: 'he' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'שלום');   // confidence 1 in this window
  engine.resetRun();          // left & returned to the same field / new burst
  native.calls.typed = '';

  typeWord(engine, 'יקךךם');  // 'hello' typed on the Hebrew layout → must correct
  assert.strictEqual(native.calls.typed.trim(), 'Hello'); // single word → capitalized
});

test('engine: does not fire on a word the dictionaries do not know', () => {
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  typeWord(engine, 'xkcd');
  assert.strictEqual(native.calls.typed, '');
});

// Drive the engine through the REAL keydown path (guards, lag gate, layout
// checks) instead of _appendChar. `time` simulates the hook thread's event
// timestamp; omit `lagMs` for a fresh event.
function pressKey(engine, keycode, { shiftKey = false, lagMs = 0 } = {}) {
  engine._onKeydown({
    keycode, shiftKey, ctrlKey: false, altKey: false, metaKey: false,
    time: Date.now() - lagMs
  });
}

test('engine: stale space event (processing lag) skips the correction instead of erasing blind', () => {
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  // 'akuo' typed through the real keydown path with fresh timestamps
  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k);
  // The space arrives 500ms late — the user may have typed more by now, so
  // injecting a correction could erase the wrong characters. Must skip.
  pressKey(engine, keymapK.Space, { lagMs: 500 });
  assert.strictEqual(native.calls.typed, '', 'late-processed space must not trigger injection');

  // A FRESH space right after corrects normally — the gate is per-event.
  pressKey(engine, keymapK.Space);
  assert.ok(native.calls.typed.includes('שלום'), 'fresh space must still correct');
});

test('engine: a wall-clock step does not permanently disable detection', () => {
  // Regression test for the "sometimes it just stops correcting" bug: the
  // lag-gate baseline was the ALL-TIME minimum of (Date.now() - event.time).
  // Date.now() is NTP-disciplined (steps on time sync / resume from sleep)
  // while hook timestamps come from the tick counter, so after any forward
  // wall-clock step >150ms every event looked "late" forever and evaluation
  // was silently skipped until the app restarted.
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  // Calibrate the baseline with fresh events (a word no dictionary knows, so
  // no correction fires and the fake layout stays 'en'), then the wall clock
  // steps forward 5s: every event from here on reports a constant 5s "lag".
  for (const k of [keymapK.X, keymapK.K, keymapK.C, keymapK.D]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);
  engine.resetRun();

  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k, { lagMs: 5000 });
  pressKey(engine, keymapK.Space, { lagMs: 5000 });
  assert.strictEqual(native.calls.typed, '', 'right after the step the gate correctly holds');

  // The apparent lag persists past LAG_RECAL_MS — real event-loop lag cannot
  // do that (processing events proves the loop is live), so the engine must
  // re-anchor its baseline and come back to life instead of staying dead.
  engine._lagSince = Date.now() - 2500;
  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k, { lagMs: 5000 });
  pressKey(engine, keymapK.Space, { lagMs: 5000 });
  assert.ok(native.calls.typed.includes('שלום'),
    'detection must recover after the clocks are re-anchored');
});

test('engine: a backward wall-clock step re-anchors immediately and detection stays live', () => {
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.X, keymapK.K, keymapK.C, keymapK.D]) pressKey(engine, k);
  pressKey(engine, keymapK.Space);
  engine.resetRun();

  // Wall clock steps BACK 5s → skew shrinks below the baseline. That must be
  // adopted as the new baseline on the spot (negative lag means "impossibly
  // early", not "late"), so the very next word still corrects.
  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k, { lagMs: -5000 });
  pressKey(engine, keymapK.Space, { lagMs: -5000 });
  assert.ok(native.calls.typed.includes('שלום'),
    'a backward clock step must not disturb detection at all');
});

test('engine: real Backspace right after a correction is processed once echoes are consumed', () => {
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  typeWord(engine, 'akuo'); // buffer is now 'שלום '
  assert.strictEqual(engine.buffer, 'שלום ');

  // The 5 Backspace echoes of our own batch ('akuo ' = 5 erases) are swallowed…
  for (let i = 0; i < 5; i++) pressKey(engine, keymapK.Backspace);
  assert.strictEqual(engine.buffer, 'שלום ', 'echo backspaces must not touch the buffer');

  // …but the SIXTH Backspace is the user's and must take effect.
  pressKey(engine, keymapK.Backspace);
  assert.strictEqual(engine.buffer, 'שלום', 'a real backspace after the echoes must be processed');
});

test('engine: blocked injection (elevated window) records nothing and eats no keys', () => {
  const native = makeFakeNative({ layout: 'en' });
  native.replaceText = () => false; // UIPI: SendInput injected nothing
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  const events = [];
  engine.on('corrected', (e) => events.push(e));

  typeWord(engine, 'akuo');

  assert.strictEqual(events.length, 0, 'no corrected event for a fix that never reached the screen');
  assert.strictEqual(engine.lastFix, null, 'nothing to revert');
  assert.strictEqual(engine._injectGuard, null, 'guard must be disarmed — no echoes are coming');
  assert.deepStrictEqual(native.calls.layoutSet, [], 'layout must not be switched');
});

test('engine: third keyboard layout (not he/en) is left completely alone', () => {
  const keymapK = require('../src/engine/keymap').UiohookKey;
  const native = makeFakeNative({ layout: 'other' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });

  for (const k of [keymapK.A, keymapK.K, keymapK.U, keymapK.O]) pressKey(engine, k);
  assert.strictEqual(engine.buffer, '', 'keystrokes on a third layout must not be modeled');
  pressKey(engine, keymapK.Space);
  assert.strictEqual(native.calls.typed, '', 'no correction may fire on a third layout');
});

test('engine: a hook event that throws inside the handler does not propagate', () => {
  const native = makeFakeNative({ layout: 'en' });
  native.getForegroundWindowId = () => { throw new Error('boom'); };
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  assert.doesNotThrow(() => pressKey(engine, require('../src/engine/keymap').UiohookKey.A));
});

test('engine: inject-guard swallows injection echoes but keeps real keystrokes', () => {
  const keymap = require('../src/engine/keymap');
  const native = makeFakeNative({ layout: 'en' });
  const engine = new AutocorrectEngine({ native, settings: makeFakeSettings() });
  engine._syncWindow();
  engine.lastKeyTime = Date.now();
  engine._armInjectGuard();

  const kd = (keycode) => engine._onKeydown({ keycode, shiftKey: false, ctrlKey: false, altKey: false, metaKey: false });

  // Echoes of our own SendInput batch (Backspace, and 0 = VK_PACKET/unicode)
  // must be ignored so they don't corrupt the buffer.
  kd(keymap.UiohookKey.Backspace);
  kd(0);
  assert.strictEqual(engine.buffer, '', 'injection echoes must not enter the buffer');

  // A REAL letter typed during the same guard window must still register —
  // this is the "typing during a correction gets swallowed" bug being fixed.
  kd(keymap.UiohookKey.A);
  assert.strictEqual(engine.buffer, 'a', 'a genuine keystroke during the guard must be kept');
});
